header-y += byteorder/
header-y += can/
header-y += caif/
header-y += dvb/
header-y += hdlc/
header-y += hsi/
header-y += isdn/
header-y += mmc/
header-y += nfsd/
header-y += raid/
header-y += spi/
header-y += sunrpc/
header-y += tc_act/
header-y += tc_ematch/
header-y += netfilter/
header-y += netfilter_arp/
header-y += netfilter_bridge/
header-y += netfilter_ipv4/
header-y += netfilter_ipv6/
header-y += usb/
header-y += wimax/

ifneq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/asm/a.out.h \
		  $(srctree)/include/asm-$(SRCARCH)/a.out.h \
		  $(INSTALL_HDR_PATH)/include/asm-*/a.out.h),)
endif
ifneq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/asm/kvm.h \
		  $(srctree)/include/asm-$(SRCARCH)/kvm.h \
		  $(INSTALL_HDR_PATH)/include/asm-*/kvm.h),)
endif
ifneq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/asm/kvm_para.h \
		  $(srctree)/include/asm-$(SRCARCH)/kvm_para.h \
		  $(INSTALL_HDR_PATH)/include/asm-*/kvm_para.h),)
endif
