#
# Makefile for Meta-specific library files.
#

lib-y = usercopy.o copy_page.o clear_page.o memcpy.o memmove.o \
	memset.o delay.o div64.o muldi3.o ashrdi3.o ashldi3.o lshrdi3.o \
	divsi3.o modsi3.o ip_fast_csum.o checksum.o
