#
# Makefile for the Linux Meta-specific sysfs interfaces.
#

obj-$(CONFIG_META_CORE_SYSFS)		+= core-sysfs.o counters/
obj-$(CONFIG_META_WRITE_COMBINER)	+= write-combiner.o
obj-$(CONFIG_META_MEM_ARBITER)		+= memory-arbiter.o
obj-$(CONFIG_META_L2C_CONTROL)		+= l2cache-control.o
