#
# Makefile for the Meta performance counter specific device drivers.
#

obj-$(CONFIG_META_CYCLE_COUNTER)	+= cyclecount.o
obj-$(CONFIG_META_PERFORMANCE_COUNTER)	+= perfcount.o
obj-$(CONFIG_META_AMA_COUNTER)		+= amacount.o
