/*
 * metac_all.inc
 *
 * Copyright (C) 2000, 2001, 2002, 2005, 2007, 2012 Imagination Technologies.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * Assembler header for fall-back target specifics
 *
 *            defines :
 *
 *             METAC_ALL - set if this header is included
 */

#ifndef METAC_ALL
#define METAC_ALL
#endif

#if 1
#ifndef _METAC_ALL_H_
#define _METAC_ALL_H_

#endif  /* #ifndef _METAC_ALL_H_ */
#endif   /* #ifdef METAC_ALL */

/* End of metac_all_ext.inc */
