#ifndef _UAPI__HW_BREAKPOINT_H__
#define _UAPI__HW_BREAKPOINT_H__

enum {
	META_HWBP_CONT_REGS_BASE = CODEB0ADDR,
	META_HWBP_CONT_REGS_STRIDE = 8,
	META_HWBP_CONT_REGS_COUNT = 20,
	META_HWBP_WRITTEN = 1,
	META_HWBP_DATA_END = -1
};


#endif /* _UAPI__HW_BREAKPOINT_H__ */
