# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

header-y += tbx/
header-y += byteorder.h
header-y += hw_breakpoints.h
header-y += mman.h
header-y += ptrace.h
header-y += resource.h
header-y += setup.h
header-y += sigcontext.h
header-y += siginfo.h
header-y += swab.h
header-y += unistd.h
